<?php

namespace OgilvyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LoginLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginLogRepository extends EntityRepository
{
}
