<?php

namespace OgilvyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WebsiteUserAccessTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteUserAccessTokenRepository extends EntityRepository
{
}
